### ISSUE TITLE
BindWindow() doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [Chunjee/graphicsearch.ahk#2]
First I'd like to thank you so much for the awesome work with this library!
Second, the function BindWindow() seems to fail when a window is on top of the search area(obscured).
If you're on AHK discord channel we can screen-share to show you what I mean exactly.

Thank you very much once again!

cheers,
yawik

**Comment by Chunjee** [comment]
Please try again with v0.4.0

BindWindow is not documented and possibly not supported yet.
