### ISSUE TITLE
Coordinates returned for wrong screen (but not when using provided GUI test)

### ISSUE THREAD

**Issue by asdasd-123** [Chunjee/graphicsearch.ahk#3]
Hi, 
I've run into a what appears to be a bug that I can't track down, but is still reproducible when searching on a 2 monitor setup. In this example, two monitors both on 1920x1080 resolution, side by side. So coordinates range from -1920,0 to 1920,1080

I'm getting the coordinates of the found images all returned for the wrong screen. 
So for example, if the image is actually at x=10|y=20, the returned coords from graphicsearch are x=-1910|y=20

The strange part is that it works fine when using the "graphicsearch_gui.ahk" test function.

Steps to reproduce the issue are as follows:
- Have 2 monitors with right monitor set to main monitor
- Open graphicsearch_gui.ahk
- Click capture, setup the greyscale, click ok
- Click Test while the image is on the main monitor (_this spits out the correct coordinates on and highlights the images correctly on the correct screen_)
- Copy the supplied code into a new ahk document and run it. This will spit out the incorrect coordinates (in my case, all X values are off by a screenwidth. Worse still is that it will not find the image at all if it's on the left monitor.

I've tried for hours to work out whats different between the gui test function and the actual library, but a lot of it goes above my head so I've had no luck.

**Comment by Chunjee** [comment]
The majority of the methods will search between 0/0, and the max screenwidth/max screenheight by default. This may be causing you unexpected results when dealing with negative coordinates.

The function associated with graphicsearch_gui.ahk is different but I will experiment as well.
Please confirm if I am understanding this right:
- two screens, the rightmost is the windows main monitor
- the graphic is on the right screen at the time of the test? Therefore a positive number is expected

**Comment by asdasd-123** [comment]
Yes, you're correct on both assumptions. 
I'll do some more digging as well. I got as far as seeing that the "allpos" results were different on each but that's where I got lost

EDIT: 
An additional note. If i try to limit the search to 0,0->1920,1080, it will fail and return no results

**Comment by asdasd-123** [comment]
I've attached both outputs i receive when searching for the same image but with both methods
![AutoHotkey_FNrjMlnugs](https://user-images.githubusercontent.com/35167513/115305928-01da9780-a15f-11eb-933c-b01e921cb2b7.png)
![X23u62adr9](https://user-images.githubusercontent.com/35167513/115305940-0737e200-a15f-11eb-8f9d-fb6c189c3bf2.png)

**Comment by Chunjee** [comment]
I'm not immediately sure how an image found on the main screen could return a negative number but configure a second monitor like that the explore.

**Comment by rafaco** [comment]
Hi, any update on this? I stopped using this library due to this issue but I would love to continue using it.


Edited: Original FindText.ahk seems to have solved this issue on version 7.7. It could give you some tips to compare changes between 7.7 and 7.6. 
```
Updated to 7.7 version - 2020/12/10
1. Modify: Images can already be found correctly on multiple displays.
2. ...
```
From https://www.autohotkey.com/boards/viewtopic.php?style=7&f=6&t=17834

**Comment by asdasd-123** [comment]
Not on my end sorry. I hunted around for a while but that part of the code gets too confusing for me. I wrote a function to parse the wrong co-ordinates through and called it a day for that project

**Comment by Chunjee** [comment]
Please try again with v0.4.0

**Comment by asdasd-123** [comment]
I've got a new project that'll need this soon so I'll give it a go then and comment back here with the outcome. 
Thanks for all your work on it so far, it's great

**Comment by Chunjee** [comment]
According to someone on Discord. v0.4.0 worked for their 2nd monitor.

**Comment by rootaman** [comment]
Please reopen this issue, I have 3 monitors and the code in the GUI works for ALL monitors when I tesed it but it will ONLY works on the main monitor when I copied and apply them with Hotkey... My 2nd monitor is located under the main one and my 3rd monitor is located at the right of the main monitor and this one has to rotate 180 degree....
