### ISSUE TITLE
Small documentation fix

### ISSUE THREAD

**Issue by ssweber** [Chunjee/graphicsearch.ahk#5]
At the first example script on https://chunjee.github.io/graphicsearch.ahk/#/tutorial?id=resultsobject

`        msgbox, % "x: " result[A_Index].x ", y: " result[A_Index].y`

should be

`        msgbox, % "x: " resultObj[A_Index].x ", y: " resultObj[A_Index].y`

That's all! Great script!

**Comment by Chunjee** [comment]
Fixed by b41e2e06b610eecfa01c56c0e481628a2371cbdd
