### ISSUE TITLE
Change capture hotkey / button

### ISSUE THREAD

**Issue by tallpeak** [Chunjee/graphicsearch.ahk#6]
Can you make the image capture hotkey (or mouse button) changeable?

I hacked my copy of your script to use ScrollLock instead of RButton, because RButton changes the state of the application I was trying to automate (removing the image I was trying to capture!) 

(Incidentally, I don't understand the GUI's hotkey settings, and don't see any mention of it in the documentation, but haven't read it all yet...)

Also, this is how I would prefer capture to work:
Hotkey to start capture and open capture box. 
Trap all keystrokes and mouse movements during capture
Arrows to resize capture box
Hotkey to stop capture.

Alternatively, the hotkey that starts capture could capture the entire screen of all monitors, then the bounding-box could be navigated over that entire captured image to find the correct location to clip. (But that seems a bit more complicated.)

**Comment by Chunjee** [comment]
I think you have multiple ideas listed in one issue so I'm having trouble labeling it.

It looks like most of these have to do with [graphicsearch_gui.ahk](https://github.com/Chunjee/graphicsearch.ahk/blob/master/graphicsearch_gui.ahk) which is not a major focus of this package.
